# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 12bef05fadcbf23b96ad2c4cee7cb3e0404efbf5569631f905d0bcd071c316c550de60a13490086d23a04411403b2e482f1dc39d669484b3a4b1c8d8af637907

test:
  secret_key_base: 491d8baa111aaeb0d3baf43e2a8d21626200a64e1832f73a4db660a37df2b8eca69ed4e3241647a143217e00b4c50be214dc6c9884f10c07f63d7e67d4b99bbe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
