# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e6b076983c6802fa7f6bb998cdc7cd48fd547e5821abfd20b27a14f68c395ffa2a946568da2b6fcfacf135c2aadd4cbc5bd0350b82525264747923191e444048

test:
  secret_key_base: 10a720f74858d7646653108a53d0f9d29e903101ef5f68e91ac7c858cbdf4d62cb0f8bbede2d30901009ba34fc0897e927707365ea66d60d70b9cf5a795d363c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
